name: Deploy to Elastic Beanstalk (AWS CLI)

on:
  push:
    branches:
      - {{cookiecutter.github_branch}}
  workflow_dispatch:

jobs:
  security-scan:
    name: Run Security Scan
    uses: ./.github/workflows/security-scan.yml
  backend-ci:
    name: Run Backend CI
    uses: ./.github/workflows/backend-ci.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [security-scan, backend-ci]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        {% raw %}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        {% endraw %}
    - name: Install AWS CLI and EB CLI
      run: |
        pip install awscli awsebcli --upgrade

    - name: Deploy to Elastic Beanstalk
      env:
        {% raw %}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        {% endraw %}
        ALLOWED_DOMAIN: graphitehq.com
      run: bash ./scripts/deploy.sh
