services:
  nginx-proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "/var/log/nginx:/var/log/nginx"
    depends_on:
      - frontend
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
    ports:
      - "3000:3000"
    entrypoint: [ "bun", "./server.js" ]
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - AUTH_URL=${AUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    {% if cookiecutter.include_database %}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    {% endif %}
    ports:
      - "8000:8000"
    entrypoint: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
  {% if cookiecutter.include_database %}
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /var/lib/postgresql
  {% endif %}
