branch-defaults:
  {{cookiecutter.github_branch}}:
    environment: {{cookiecutter.eb_environment}}
    group_suffix: null
global:
  application_name: {{cookiecutter.eb_app_name}}
  branch: null
  default_ec2_keyname: ricardo-2-kp
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
